development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://idadrijbgchaon:snL97Zneqz92V_xJNrL8sU7UMb@ec2-54-243-47-213.compute-1.amazonaws.com:5432/dd6atf73ddvr4p
